name: Run tests for scripting projects
description: |
  This action detects automated tests for some common scripting language test frameworks and runs them.
inputs:
  include-optional-dependencies:
    description: Flag whether to also clone and include in PATH dependencies marked as optional.
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Checkout scripting-testrunner dependencies
      uses: actions/checkout@v4
      with:
        repository: inkarkat/shell-filesystem
        path: .scripting-testrunner/shell-filesystem
    - name: Checkout dependencies
      env:
        INCLUDE_OPTIONAL_DEPENDENCIES: ${{ fromJSON(inputs.include-optional-dependencies) && 't' || '' }}
      run: |
        export PATH="${GITHUB_ACTION_PATH}/bin:${PATH}"
        mkdir --parents -- "${GITHUB_WORKSPACE}/dependencies"
        cd "${GITHUB_WORKSPACE}/dependencies"
        checkoutGitDependencies ${INCLUDE_OPTIONAL_DEPENDENCIES:+--include-optional} --recursive README.md -- "${GITHUB_WORKSPACE}/README.md"
      shell: bash
    - name: Run scripting tests
      run: |
        cp --force -- "${GITHUB_WORKSPACE}/.scripting-testrunner/shell-filesystem/bin/hasMatchingFile" "${GITHUB_ACTION_PATH}/bin"
        for dependencyPath in "${GITHUB_WORKSPACE}/dependencies"/*
        do
          dependencyBin="${dependencyPath}/bin"
          if [ -d "$dependencyBin" ]; then
            PATH="${dependencyBin}:${PATH}"
            printf 'Add dependency %s\n' "$dependencyBin"
          fi
        done
        export PATH="${PWD}/bin:${GITHUB_ACTION_PATH}/bin:${PATH}"
        RUNTESTSIN_RUN_PREFIX='::group::' \
        RUNTESTSIN_RUN_SUFFIX='::endgroup::' \
        EACHCOMPONENTDO_SETUP_PREFIX='::group::' \
        EACHCOMPONENTDO_SETUP_SUFFIX='::endgroup::' \
          runTests "${PWD}/tests"/*
      shell: bash
