name: Run tests for scripting projects
description: |
  This action detects automated tests for some common scripting language test frameworks and runs them.
runs:
  using: composite
  steps:
    - name: Checkout git-extensions
      uses: actions/checkout@v4
      with:
        repository: inkarkat/shell-filesystem
        path: .scripting-testrunner/shell-filesystem
    - name: Run scripting tests
      run: |
        cp --force -- "${GITHUB_WORKSPACE}/.scripting-testrunner/shell-filesystem/bin/hasMatchingFile" "${GITHUB_ACTION_PATH}/bin"
        export PATH="${PWD}/bin:${GITHUB_ACTION_PATH}/bin:${PATH}"
        RUNTESTSIN_RUN_PREFIX='::group::' \
        RUNTESTSIN_RUN_SUFFIX='::endgroup::' \
        EACHCOMPONENTDO_SETUP_PREFIX='::group::' \
        EACHCOMPONENTDO_SETUP_SUFFIX='::endgroup::' \
          runTests "${PWD}/tests"/*
      shell: bash
